### ISSUE TITLE
Redirect to subdirectory

### ISSUE THREAD

**Issue by rayshan** [rafrex/spa-github-pages#1]
Hi Rafael, thanks for putting this together.

Let's say the user has a [user page](https://github.com/rayshan/rayshan.github.io) with a [custom domain](https://shan.io), and the user is serving a [SPA in a subdirectory](https://shan.io/photography/).  Would this solution redirect to the root of the subdirectory? Maybe a base url option can be exposed?

**Comment by rafgraph** [comment]
The problem is that you can only have one 404.html file for your site. If you want all 404s to redirect to subdirectory with your spa (and let that spa handle all 404s, both redirects and actual page not founds), then you can tweak the script in 404.html to something like:

``` javascript
      var l = window.location;
      l.replace(
        l.protocol + '//' + l.hostname + (l.port ? ':' + l.port : '') +
        '/your-subdirectory' + // ADD THIS LINE
        '/?' + 'redirect=true' +
        // DON'T INCLUDE /your-subdirectory IN REDIRECT QUERY
        (l.pathname ? '&pathname=' + l.pathname.replace('/your-subdirectoy', '').replace(/\//g, '%2F').replace(/&/g, '%26') : '') +
        (l.search ? '&query=' + l.search.replace(/\//g, '%2F').replace(/&/g, '%26') : '') +
        l.hash
      );
```

...and tweak the script in index.html (that's served out of `/your-subdirectory`) to something like:

``` javascript
      (function(l) {
        if (l.search) {
          var q = {};
          l.search.slice(1).split('&').forEach(function(v) {
            var a = v.split('=');
            q[a[0]] = a.slice(1).join('=').replace(/%2F/g, '/').replace(/%26/g, '&');
          });
          if (q.redirect === 'true') {
            window.history.replaceState(null, null,
              '/your-subdirectory' + // ADD THIS LINE
              (q.pathname || '') +
              (q.query || '') +
              l.hash
            );
          }
        }
      }(window.location))
```

You could also add more advanced logic instead of just `your-subdirectory`. For example, you could re-route to multiple different subdirectories (based on the url the user attempted to access), each with it's own spa, as long as the paths to the subdirectories can be hard coded into the redirect scripts.

**Comment by rayshan** [comment]
That makes sense, thanks. I'll move the SPA to a subdomain like `photography.shan.io` to keep things clean.
