### ISSUE TITLE
Url with dashes don't seem to work

### ISSUE THREAD

**Issue by gbanis** [rafrex/spa-github-pages#10]
Thanks so much for putting this together, this is so helpful!

I implemented your solution and all urls work like a charm.

However, paths with dashes, for example `example.com/some-path` show me github's 404 page (not mine) and therefore don't redirect to the spa's route.

**Comment by rafgraph** [comment]
I don't believe this is an issue with `spa-github-pages` as http://spa-github-pages.rafrex.com/some-path works as it should (shows the the spa's page not found page, not GitHub's).

Also, when I goto http://rc.gbanis.com/some-path, the redirect appears to be working fine (nothing is shown on the page, but your app loaded).

If you are still having this issue please provide an example where it loads GitHub's 404 page instead of the redirect and I'll take a look.
