### ISSUE TITLE
Routes not updating view

### ISSUE THREAD

**Issue by bogas04** [rafrex/spa-github-pages#11]
Hey! First off, this tip is really cool !

Now here's my setup;

* repo @ bogas04.github.io/SikhJS
* master branch is used for gh-page
* My [Routes](https://github.com/bogas04/SikhJS/blob/browserHistory/js/routes.js)
* [index.html](https://github.com/bogas04/SikhJS/blob/browserHistory/index.html#L17-L34)
* [404.html](https://github.com/bogas04/SikhJS/blob/browserHistory/404.html)
* [Links](https://github.com/bogas04/SikhJS/blob/browserHistory/js/components/Main/index.js#L39-L46) within code.

I think it pretty much checks off all todos to make this work, but for some reason my Links aren't rerendering any component on click. It might be related to react-router; my understanding is that browserHistory and user.github.io/repo URLs are not playing nicely for some reason.
Since you already know about this use case, can guide me what might be wrong ?

**Comment by rafgraph** [comment]
You need to prefix your routes and links with `repo-name`, e.g. 
`<Route path="/repo-name/authors" component={Authors} />`
`<Link to="/repo-name/authors">Authors</Link>`

**Comment by bogas04** [comment]
Thank you so much for taking out time to read the code.

That surely sucks to hardcode the repo in routes, but then whole thing is a workaround in the first place.

You're the best !

**Comment by rafgraph** [comment]
Actually needing the `repo-name` in Routes and Links is not because of the workaround. Even if GitHub Pages natively supported single page apps, you would still need the `repo-name` prefix because React Router's job is to keep the UI in sync with the URL path, the full URL path, and as long as the site's address is `https://username.github.io/repo-name`, the Routes and Links will need to include `repo-name`.

For Routes, you can use nested Routes where the outer Route has `path="/repo-name/"`, and all the nested Routes use relative paths, like `path="authors"`. But for Links you always have specify the full absolute path.

**Comment by bogas04** [comment]
> as long as the site's address is https://username.github.io/repo-name

I guess I should really go for custom domain to keep things clean.

> For Routes, you can use nested Routes where the outer Route has path="/repo-name/", and all the nested Routes use relative paths, like path="authors". But for Links you always have specify the full absolute path.

Yeah I tried that but then for some reason view was not updating.
