### ISSUE TITLE
Syntax error for BrowserRouter

### ISSUE THREAD

**Issue by ambershen** [rafrex/spa-github-pages#20]
when I try to run `npm run build`, it always return me a compiling error:
![image](https://user-images.githubusercontent.com/13397058/29038281-0877f8a8-7b5c-11e7-9007-c32e24c2c50a.png)

don't know how to solve this

**Comment by rafgraph** [comment]
This is mostly likely because React in not in scope or Babel is not setup properly.

I just tried cloning the repo and running `npm install` and then `npm run build` and it worked fine. Do you still have this problem with a fresh clone, install and build without changing any of the files?

**Comment by dgurns** [comment]
I'm getting the same error, even after updating Node and NPM to latest versions. `npm run build` fails with the following error message:

<img width="568" alt="screen shot 2018-03-30 at 11 24 36 am" src="https://user-images.githubusercontent.com/1173791/38143079-f6848b74-340c-11e8-91ef-79bcb7b40489.png">

UPDATE: This was happening because the .babelrc did not clone initially. I had to manually add it to my local repo. Now everything works.
