### ISSUE TITLE
less hacky with `encodeURIComponent` and `decodeURIComponent` instead?

### ISSUE THREAD

**Issue by choonkeat** [rafrex/spa-github-pages#31]
``` diff
- s.replace(/&/g, '~and~')
+ encodeURIComponent(s)
```

and

``` diff
- s.replace(/~and~/g, '&')
+ decodeURIComponent(s)
```

**Comment by rafgraph** [comment]
Thanks for the suggestion. The reason I don't use this is for readability because the encoded url is what gets indexed by search engines and shows up in search results. For example, `/one/two?a=b&c=d` would get turned into `/?%2Fone%2Ftwo&a%3Db%26c%3Dd` using `encodeURIComponent`, compared to `/?/one/two&a=b~and~c=d`.
