### ISSUE TITLE
Project and User/Organization Pages

### ISSUE THREAD

**Issue by websemantics** [rafrex/spa-github-pages#8]
Hi and thank you for this project,

I had an issue with running the code on a Project Pages type Github repository, I also thought it would be easier for people to import from Bower / Node,

So here's an Npm/Bower package of your code slightly modified to support [Project and User Org Pages](https://help.github.com/articles/user-organization-and-project-pages/)

https://github.com/websemantics/gh-pages-spa

**Comment by rafgraph** [comment]
If it's a project pages site, then you have to use a custom domain in order for GitHub Pages to serve a custom 404 page. I talk a bit about how to set this up in the [instructions](https://github.com/rafrex/spa-github-pages#usage-instructions) with links to GitHub docs.

**Comment by websemantics** [comment]
Thanks for your reply, 

When I first used the code, I had all the url after the main domain, for example, `https://username.github.io/repo/foo` turned into query-string >> `https://username.github.io?p=repo/foo`, this didn't work well for Project Pages where the `repo` name should stay, .. I might be missing on something here,

**Comment by rafgraph** [comment]
You're right, ~~but it's a moot point because you must use a custom domain for GitHub Pages to serve a custom 404 page for a Project Pages site, [see here](https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/), and the custom domain won't have `/repo` at the beginning of the path.~~

I did a few tests this morning and it appears that GitHub Pages now serves a custom 404 page for Project Pages sites without using a custom domain (despite the [docs still indicating the opposite](https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/)). I'll reopen the issue and update the redirect scripts. Thanks for the heads up @websemantics.

Also, don't forget to include author cred along with my code in [ghspa.js](https://github.com/websemantics/gh-pages-spa/blob/780cd6e5e28e1537961133d3ed613adb698b1054/ghspa.js).

**Comment by rafrex** [comment]
Also, by putting the redirect scripts in a separate `ghspa.js` file instead of directly in the html files, you're adding two extra, and unnecessary, server requests. For example, to goto `example.tld/page`, the initial request will return the `404.html` which will make a request for the redirect script, and only after the script is loaded from the server will the request be made with the redirect query that returns `index.html`, and then another request is made to the server for the redirect script, and only after it loads and runs will the correct url be available to the single page app.

**Comment by rafgraph** [comment]
Fixed. Just set `pathPrefix` to true [here](https://github.com/rafrex/spa-github-pages/blob/gh-pages/404.html#L27) and it will work with Project Pages sites not using a custom domain. Also updated the readme, so check that out for more info.

Let me know if you have any issues with this.

**Comment by rafgraph** [comment]
Just got confirmation from GitHub support that GitHub Pages now serves a custom 404 page for Project Pages sites without using a custom domain (GitHub docs are outdated and will be updated).

**Comment by websemantics** [comment]
I never read the docs, ignorance -sometimes- is a bless hh 

I already had a link to your repo in the original [README.md](https://github.com/websemantics/gh-pages-spa) and now clearly in [ghspa.js](https://github.com/websemantics/gh-pages-spa/blob/master/ghspa.js),

The only added contribution I had was the switch between **Project Pages** and **User/Org pages** which your library now supports too, 

I also had it packaged as Bower/Node package, and the setup/steps are slightly easier to follow (maybe),
- Include  [ghspa.js](https://github.com/websemantics/gh-pages-spa/blob/master/ghspa.js) in `index.html` and `404.html`
- Set the _title_ of `404.html` to `404`
- Done,

If you could probably make it as such, I really don't need that repo,

Thanks @rafrex for the original contribution,

**Comment by websemantics** [comment]
Oh, and a really [fancy demo page](https://websemantics.github.io/gh-pages-spa/) which took way longer to build than writing code hhh
